export enum ActionTypeEnum {
  // DRAG_PRESET = "DRAG_PRESET",

  ADD_OBJECT = "ADD_OBJECT",
  REMOVE_OBJECT = "REMOVE_OBJECT",

  SELECT_OBJECT = "SELECT_OBJECT",
  UNSELECT_OBJECT = "UNSELECT_OBJECT",

  MODIFY_OBJECT = "MODIFY_OBJECT",
}
